import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTables1710399560778 implements MigrationInterface {
    name = 'CreateTables1710399560778'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comment" ("id" SERIAL NOT NULL, "content" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_0b0e4bbc8415ec426f87f3a88e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "blog" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "paragraph" character varying NOT NULL, "status" "public"."blog_status_enum" NOT NULL DEFAULT 'approving', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userInfo_id" integer, CONSTRAINT "PK_85c6532ad065a448e9de7638571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "userInfo" ("id" SERIAL NOT NULL, "fistName" character varying NOT NULL DEFAULT '', "lastName" character varying NOT NULL DEFAULT '', "phoneNumber" character varying NOT NULL DEFAULT '', "isActive" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "REL_645e77e7feb4541c205eb3ffdd" UNIQUE ("user_id"), CONSTRAINT "PK_2a191c92ffee9d860da37038ae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "keyToken" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "refreshTokenUsed" text NOT NULL DEFAULT '', "refreshTokenUsing" character varying NOT NULL, "user_id" uuid, CONSTRAINT "REL_82ec2cad0a6b52b1f115e22b77" UNIQUE ("user_id"), CONSTRAINT "PK_2f965b2a505823d42065c997118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "blog_comment" ("blog_id" integer NOT NULL, "comment_id" integer NOT NULL, CONSTRAINT "PK_bf6cbe4fde9ee4f0b0dc79463f7" PRIMARY KEY ("blog_id", "comment_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2e06d1f23800610fb9f3715c4" ON "blog_comment" ("blog_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eb9736ace8af415368a3a1949" ON "blog_comment" ("comment_id") `);
        await queryRunner.query(`ALTER TABLE "comment" ADD CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blog" ADD CONSTRAINT "FK_d3ffca7f560f12dfb65cc17647c" FOREIGN KEY ("userInfo_id") REFERENCES "userInfo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "userInfo" ADD CONSTRAINT "FK_645e77e7feb4541c205eb3ffdde" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "keyToken" ADD CONSTRAINT "FK_82ec2cad0a6b52b1f115e22b772" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "blog_comment" ADD CONSTRAINT "FK_a2e06d1f23800610fb9f3715c45" FOREIGN KEY ("blog_id") REFERENCES "blog"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "blog_comment" ADD CONSTRAINT "FK_4eb9736ace8af415368a3a19493" FOREIGN KEY ("comment_id") REFERENCES "comment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "userInfo"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "blog_comment" DROP CONSTRAINT "FK_4eb9736ace8af415368a3a19493"`);
        await queryRunner.query(`ALTER TABLE "blog_comment" DROP CONSTRAINT "FK_a2e06d1f23800610fb9f3715c45"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "keyToken" DROP CONSTRAINT "FK_82ec2cad0a6b52b1f115e22b772"`);
        await queryRunner.query(`ALTER TABLE "userInfo" DROP CONSTRAINT "FK_645e77e7feb4541c205eb3ffdde"`);
        await queryRunner.query(`ALTER TABLE "blog" DROP CONSTRAINT "FK_d3ffca7f560f12dfb65cc17647c"`);
        await queryRunner.query(`ALTER TABLE "comment" DROP CONSTRAINT "FK_bbfe153fa60aa06483ed35ff4a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb9736ace8af415368a3a1949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2e06d1f23800610fb9f3715c4"`);
        await queryRunner.query(`DROP TABLE "blog_comment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "keyToken"`);
        await queryRunner.query(`DROP TABLE "userInfo"`);
        await queryRunner.query(`DROP TABLE "blog"`);
        await queryRunner.query(`DROP TABLE "comment"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
